# see https://docs.readthedocs.io/en/stable/config-file/
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: doc/conf.py
