name: Build aubio wheels for OS X (Intel)

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.9.x] # Add other versions as needed
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        brew install pkg-config gnupg
        brew install sox ffmpeg libsndfile libvorbis flac lcov 
        pip install cibuildwheel numpy

    - name: Build wheels
      run: |
        cibuildwheel --output-dir wheelhouse

    - name: Test wheels
      run: |
        pip install wheelhouse/*.whl
        python -c "import aubio; print(aubio.__version__)"

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./wheelhouse/*.whl
