name: Build aubio wheels for OS X (Intel)

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        
        python: [3.8.x,3.9.x,3.10.x,3.11.x] # 3.12.x
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        brew install pkg-config gnupg
        brew install sox ffmpeg libsndfile libvorbis flac lcov 
        pip install wheel numpy

    - name: Make aubio
      run: |
        make
    
    - name: Build wheels for ${{ matrix.python }}
      run: |
        python setup.py bdist_wheel build_ext --include-dirs=~/work/aubio/aubio/build/include --library-dirs=~/work/aubio/aubio/build/lib --libraries=aubio --extra-link-args=-static
    - name: Test wheels  for ${{ matrix.python }}
      run: |
        pip install dist/*.whl
        python -c "import aubio; print(aubio.__version__)"
  
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist/*.whl